# 데이터 분석 패키지

In [2]:
import numpy as np

In [5]:
data = [0, 1, 2, 3, 4, 5]
a1 = np.array(data)
a1

array([0, 1, 2, 3, 4, 5])

In [7]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [8]:
a1.dtype

dtype('int32')

In [10]:
a2.dtype

dtype('float64')

In [11]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [12]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [25]:
b2 = np.arange(5)
b2.shape

(5,)

In [27]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [28]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
str_1 = np.array(['1.5', '0.65', '2', '4.14', '3.14159265'])
num_1 = str_1.astype(float)
num_1

array([1.5       , 0.65      , 2.        , 4.14      , 3.14159265])

In [39]:
str_1.dtype

dtype('<U10')

In [40]:
num_1.dtype

dtype('float64')

In [45]:
num_f1 = np.array([10,21,0.459,4.75,5.98])

In [46]:
num_i = num_f1.astype(int)
num_i

array([10, 21,  0,  4,  5])

In [47]:
num_i.dtype

dtype('int32')

In [48]:
np.random.rand()

0.5138398305002273

In [49]:
np.random.rand(2, 3)

array([[0.26527776, 0.45524276, 0.39230456],
       [0.37179922, 0.48452836, 0.9240566 ]])

In [50]:
np.random.rand(2,3,4)

array([[[0.83934513, 0.70324566, 0.16101435, 0.29406609],
        [0.20733427, 0.81988019, 0.13172282, 0.90303993],
        [0.75283988, 0.85589411, 0.95630497, 0.14056692]],

       [[0.63324741, 0.88502883, 0.79141727, 0.75245754],
        [0.06142591, 0.17769265, 0.33100394, 0.10350809],
        [0.85165299, 0.20881024, 0.31602487, 0.10980464]]])

In [51]:
np.random.randint(10, size=(3,4))

array([[2, 9, 2, 2],
       [6, 5, 9, 4],
       [1, 7, 7, 7]])

In [53]:
np.random.randint(1, 30)

13

In [60]:
for i in range(6):
    i = np.random.randint(1, 45)
    print(i)

41
3
32
29
14
13


In [62]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [63]:
arr1 + arr2

array([11, 22, 33, 44])

In [64]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [65]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [66]:
arr1 / (arr2*2)

array([5., 5., 5., 5.])

In [67]:
arr1 > 20

array([False, False,  True,  True])

In [68]:
arr3 = np.arange(5)

In [69]:
arr3

array([0, 1, 2, 3, 4])

In [70]:
arr3.sum()

10

In [71]:
arr3.mean()

2.0

In [73]:
arr3.std()

1.4142135623730951

In [74]:
arr3.var()

2.0

In [76]:
a = np.array([0,1,2,3]).reshape(2,2)

In [77]:
a

array([[0, 1],
       [2, 3]])

In [78]:
b = np.array([3,2,0,1]).reshape(2,2)
b

array([[3, 2],
       [0, 1]])

In [79]:
a.dot(b)

array([[0, 1],
       [6, 7]])

In [80]:
np.dot(a,b)

array([[0, 1],
       [6, 7]])

In [82]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [83]:
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [84]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [85]:
a1[0]

0

In [86]:
a1[4]

40

In [87]:
a1[5] = 100
a1

array([  0,  10,  20,  30,  40, 100])

In [88]:
a1[[1,3,4]]

array([10, 30, 40])

In [89]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [90]:
a2[0,2]

30

In [91]:
a2[2, 2]

90

In [92]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [93]:
a2[1]

array([40, 50, 60])

In [95]:
a2[1] = np.array([34, 55, 77])

## 

In [96]:
a2

array([[10, 20, 30],
       [34, 55, 77],
       [70, 80, 90]])

In [97]:
a2[[0,2], [0,1]]

array([10, 80])

In [98]:
a = np.array([1,2,3,4,5,6])
a[a > 3]

array([4, 5, 6])

In [99]:
a[(a%2) ==0 ]

array([2, 4, 6])

In [100]:
a[1:4]

array([2, 3, 4])

In [101]:
a[:3]

array([1, 2, 3])

In [102]:
a[2:]

array([3, 4, 5, 6])

In [104]:
a[2:5] = [25, 33, 55]
a

array([ 1,  2, 25, 33, 55,  6])

In [105]:
a[2:5] = 60
a

array([ 1,  2, 60, 60, 60,  6])

In [107]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [108]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [110]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [111]:
b2[1][0:2]

array([40, 50])

In [112]:
b2[0:2, 1:3]

array([[20, 30],
       [50, 60]])

In [113]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])

In [114]:
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

# 판다스


In [115]:
import pandas as pd

In [116]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [117]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [118]:
s1.values
print(s1.values)

[10 20 30 40 50]


In [119]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [120]:
s3 = pd.Series([np.nan, 20, 30])
s3

0     NaN
1    20.0
2    30.0
dtype: float64

In [123]:
index_date = ['2020-02-10', '2020-03-01', '2020-07-10', '2020-12-25']
s4 = pd.Series([200, 195, np.nan, 205], index = index_date )
s4

2020-02-10    200.0
2020-03-01    195.0
2020-07-10      NaN
2020-12-25    205.0
dtype: float64

In [126]:
s5 =  pd.Series({'2020-02-10':200, '2020-03-01':195})

In [127]:
s5

2020-02-10    200
2020-03-01    195
dtype: int64

In [128]:
pd.date_range(start='2020-01-01', end='2020-01-10')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [129]:
pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [130]:
data_list = np.array([[10,20,30], [140,50,60], [70,80,90]])

In [131]:
pd.DataFrame(data_list)

0   1   2
0   10  20  30
1  140  50  60
2   70  80  90

In [135]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index_data = pd.date_range('2020-07-24', periods=4)
columns_list = ['A', 'B', 'C']
pd.DataFrame(data, index=index_date, columns=columns_list)

A   B   C
2020-02-10   1   2   3
2020-03-01   4   5   6
2020-07-10   7   8   9
2020-12-25  10  11  12

In [158]:
data = np.array([[2020, '한국', 1000], [2021, '한국', 1500], [2022, '미국', 500], [2023, '한국', 1300]])
columns = np.array(['연도','지사', '고객수'])
pd.DataFrame(data, columns = columns)

연도  지사   고객수
0  2020  한국  1000
1  2021  한국  1500
2  2022  미국   500
3  2023  한국  1300

In [160]:
table_data = {'연도':[2020,2021,2022,2023],
             '지사':['한국','한국','미국', '한국'],
             '고객수':[1000, 1500, 500, 1300]}
table_data
pd.DataFrame(table_data)

연도  지사   고객수
0  2020  한국  1000
1  2021  한국  1500
2  2022  미국   500
3  2023  한국  1300

In [ ]:
pd.DataFrame(data = '연도':[2020,'한국',1000])

In [ ]:
class pandas:
    
    def DataFrame(self,data,colums,index,....)
    
    def DataFrame(self,data, colums)
    
    def DataFrame(self,data)